config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'pages#index'
  get '' => 'pages#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'admin_signup' => 'cmsusers#new'
  post 'admin_signup' => 'cmsusers#create'

  resources :sports
  resources :groups

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  namespace :api, defaults: { format: :json } do
    namespace :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, param: :username, only: [:create, :show, :update]
      post 'users/:uid/login' => 'users#fblogin', as: :fblogin
      post 'users/login' => 'users#login', as: :login

      get 'users/:username/avatar' => 'users#getavatar', as: :getavatar
      post 'users/:username/avatar' => 'users#postavatar', as: :postavatar

      get 'users/:username/cover' => 'users#getcover', as: :getcover
      post 'users/:username/cover' => 'users#postcover', as: :postcover

      post 'username/change/:username' => 'users#changeusername'

      post 'follows/:username' => 'follows#create', as: :follow
      delete 'follows/:username' => 'follows#destroy', as: :unfollow
      get 'users/:username/followers' => 'follows#followers', as: :followers
      get 'users/:username/following' => 'follows#following', as: :following

      resources :sports, only: [:index]
      get 'sports/:username/preference' => 'sports#usersports', as: :usersports
      post 'sports/:username/preference' => 'sports#likesports', as: :likesports
      delete 'sports/:username/preference' => 'sports#unlikesports', as: :unlikesports

      resources :groups, only: [:index, :create, :show, :update]
      get 'groups/page/:page' => 'groups#index'
      get 'groups/sports/:sport_id' => 'groups#index'
      get 'groups/sports/:sport_id/page/:page' => 'groups#index'
      post 'groups/join' => 'memberships#create'
      post 'groups/leave' => 'memberships#destroy'
      get 'groups/:id/requests' => 'memberships#getrequest'
      post 'groups/:id/requests/:request_id/:action_name' => 'memberships#approverequest'
      get 'users/groups/joined' => 'groups#joined'
      get 'users/groups/joined/page/:page' => 'groups#joined'
      get 'users/groups/joined/sports/:sport_id' => 'groups#joined'
      get 'users/groups/joined/sports/:sport_id/page/:page' => 'groups#joined'
      post 'memberships/:id/promote' => 'memberships#promote'
      post 'memberships/:id/demote' => 'memberships#demote'
      post 'memberships/:id/kick' => 'memberships#kick'
      
      resources :posts, only: [:create, :destroy]
      get 'groups/:group_id/posts' => 'posts#listgrouppost'
      get 'groups/:group_id/posts/page/:page' => 'posts#listgrouppost'
      get 'users/:username/posts' => 'posts#listuserpost'
      get 'users/:username/posts/page/:page' => 'posts#listuserpost'
      get 'feeds' => 'posts#listfeed'
      get 'feeds/page/:page' => 'posts#listfeed'

      resources :comments, only: [:destroy]
      post 'posts/:post_id/comments' => 'comments#create'
      get 'posts/:post_id/comments' => 'comments#postcomments'
      get 'posts/:post_id/comments/page/:page' => 'comments#postcomments'

      resources :answeredquestions, only: [:create, :update], param: :questionkey

      get 'verifymobile/:mobile_no' => 'mobile_phones#createPin'
      get 'verifymobile/:mobile_no/:pin' => 'mobile_phones#verifyPin'

      resources :events, only: [:create, :show, :update]
      post 'events/:id/:action_name' => 'attendants#invitation_response'
      get 'events' => 'events#index'
      get 'events/page/:page' => 'events#index'
      get 'events/sports/:sport_id' => 'events#index'
      get 'events/sports/:sport_id/page/:page' => 'events#index'
      get 'users/events/going' => 'events#going'
      get 'users/events/going/page/:page' => 'events#going'
      get 'users/events/going/sports/:sport_id' => 'events#going'
      get 'users/events/going/sports/:sport_id/page/:page' => 'events#going'

      post 'contactlists' => 'contactlist#searchfriends'
    end
  end

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  # main
  has_many :groups

  # attr_accessible :fileBg, :fileCover, :fileIcon
  has_attached_file :fileBg, styles: { large: "960", medium: "640", small: "320", thumb: "100" }
  has_attached_file :fileCover, styles: { large: "960", medium: "640", small: "320", thumb: "100" }
  has_attached_file :fileIcon, styles: { large: "960", medium: "640", small: "320", thumb: "100", square: "200x200!" }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :fileBg, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :fileCover, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :fileIcon, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :name
  validates_presence_of :detail

  # To_Json
  def imgBg
    fileBg.url(:original)
  end

  def imgCover
    fileCover.url(:original)
  end

  def imgIcon
    fileIcon.url(:original)
  end

  def as_json(options={})
    super(:only => [:id, :name, :detail, :sort, :updated_at],
          :methods => [:imgBg, :imgCover, :imgIcon]
    )
  end
end

app/controllers/api/v1/sports_controller.rb
class Api::V1::SportsController < Api::ApiController
  respond_to :json

  before_action :authenticate, :only => [:likesports, :unlikesports]

  # GET /sports
  def index
    @sports = Sport.all
    respond_with do |format|
      format.json { render :json => { :success => true, :data => @sports, :message => 'Sports list successfully.', :code => "4001" } }
    end
  end

  def usersports
    username = params[:username]
    @user = User.where(username: username).first if username

    unless @user
      respond_with do |format|
        format.json { render :json => { :success => false, :message => 'Invalid user.', :code => "4002" }, status: :unauthorized }
      end
    else
      @sports = Sportspref.where(user_id: @user.id)
      respond_with do |format|
        format.json { render :json => { :success => true, :data => @sports, :message => 'User\'s interest list successfully.', :code => "4003" }, status: :ok }
      end
    end
  end

  def likesports
    username = params[:username]
    sports = params[:sports]
    accesskey = request.headers['X-Access-Key']
    @user = User.where(accesskey: accesskey, username: username).first if accesskey && username

    unless @user
      respond_with do |format|
        format.json { render :json => { :success => false, :message => 'Invalid user.', :code => "4002" }, status: :unauthorized }
      end
    else
      sports.each do |sport|
        if Sportspref.where(user_id: @user.id, sport_id: sport).count <= 0
          @sportspref = Sportspref.create :user_id => @user.id, :sport_id => sport
        end
      end

      usersports
    end
  end

  def unlikesports
    username = params[:username]
    sports = params[:sports]
    accesskey = request.headers['X-Access-Key']
    @user = User.where(accesskey: accesskey, username: username).first if accesskey && username

    unless @user
      respond_with do |format|
        format.json { render :json => { :success => false, :message => 'Invalid user.', :code => "4002" }, status: :unauthorized }
      end
    else
      sports.each do |sport|
        if @sportspref = Sportspref.where(user_id: @user.id, sport_id: sport).first
          @sportspref.destroy
        end
      end

      usersports
    end
  end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:name, :detail, :fileBg, :fileCover, :fileIcon, :sort)
    end
end

app/helpers/api/v1/sports_helper.rb
module Api::V1::SportsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport, multipart: true) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.number_field :sort %>
  </div>

    <div class="field">
      <%= f.label :fileBg %><br>
      <%= f.file_field :fileBg %>
    </div>
    <div class="field">
      <%= f.label :fileCover %><br>
      <%= f.file_field :fileCover %>
    </div>
    <div class="field">
      <%= f.label :fileIcon %><br>
      <%= f.file_field :fileIcon %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Imgbg</th>
      <th>Imgcover</th>
      <th>Imgicon</th>
      <th>Sort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.name %></td>
        <td><%= sport.detail %></td>

        <td><%= sport.sort %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @sport.detail %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @sport.sort %>
</p>

<p>
  <strong>Imgbg:</strong>
  <%= image_tag @sport.fileBg.url %>
</p>

<p>
  <strong>Imgcover:</strong>
  <%= image_tag @sport.fileCover.url(:small) %>
</p>

<p>
  <strong>Imgicon:</strong>
  <%= image_tag @sport.fileIcon.url(:square) %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>