config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'pages#index'
  get '' => 'pages#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'admin_signup' => 'cmsusers#new'
  post 'admin_signup' => 'cmsusers#create'

  resources :sports
  resources :groups

  get '/api' => redirect('/swagger/dist/index.html?url=/apidocs/api-docs.json')

  namespace :api, defaults: { format: :json } do
    namespace :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users, param: :username, only: [:create, :show, :update]
      post 'users/:uid/login' => 'users#fblogin', as: :fblogin
      post 'users/login' => 'users#login', as: :login

      get 'users/:username/avatar' => 'users#getavatar', as: :getavatar
      post 'users/:username/avatar' => 'users#postavatar', as: :postavatar

      get 'users/:username/cover' => 'users#getcover', as: :getcover
      post 'users/:username/cover' => 'users#postcover', as: :postcover

      post 'username/change/:username' => 'users#changeusername'

      post 'follows/:username' => 'follows#create', as: :follow
      delete 'follows/:username' => 'follows#destroy', as: :unfollow
      get 'users/:username/followers' => 'follows#followers', as: :followers
      get 'users/:username/following' => 'follows#following', as: :following

      resources :sports, only: [:index]
      get 'sports/:username/preference' => 'sports#usersports', as: :usersports
      post 'sports/:username/preference' => 'sports#likesports', as: :likesports
      delete 'sports/:username/preference' => 'sports#unlikesports', as: :unlikesports

      resources :groups, only: [:index, :create, :show, :update]
      get 'groups/page/:page' => 'groups#index'
      get 'groups/sports/:sport_id' => 'groups#index'
      get 'groups/sports/:sport_id/page/:page' => 'groups#index'
      post 'groups/join' => 'memberships#create'
      post 'groups/leave' => 'memberships#destroy'
      get 'groups/:id/requests' => 'memberships#getrequest'
      post 'groups/:id/requests/:request_id/:action_name' => 'memberships#approverequest'
      get 'users/groups/joined' => 'groups#joined'
      get 'users/groups/joined/page/:page' => 'groups#joined'
      get 'users/groups/joined/sports/:sport_id' => 'groups#joined'
      get 'users/groups/joined/sports/:sport_id/page/:page' => 'groups#joined'
      post 'memberships/:id/promote' => 'memberships#promote'
      post 'memberships/:id/demote' => 'memberships#demote'
      post 'memberships/:id/kick' => 'memberships#kick'
      
      resources :posts, only: [:create, :destroy]
      get 'groups/:group_id/posts' => 'posts#listgrouppost'
      get 'groups/:group_id/posts/page/:page' => 'posts#listgrouppost'
      get 'users/:username/posts' => 'posts#listuserpost'
      get 'users/:username/posts/page/:page' => 'posts#listuserpost'
      get 'feeds' => 'posts#listfeed'
      get 'feeds/page/:page' => 'posts#listfeed'

      resources :comments, only: [:destroy]
      post 'posts/:post_id/comments' => 'comments#create'
      get 'posts/:post_id/comments' => 'comments#postcomments'
      get 'posts/:post_id/comments/page/:page' => 'comments#postcomments'

      resources :answeredquestions, only: [:create, :update], param: :questionkey

      get 'verifymobile/:mobile_no' => 'mobile_phones#createPin'
      get 'verifymobile/:mobile_no/:pin' => 'mobile_phones#verifyPin'

      resources :events, only: [:create, :show, :update]
      post 'events/:id/:action_name' => 'attendants#invitation_response'
      get 'events' => 'events#index'
      get 'events/page/:page' => 'events#index'
      get 'events/sports/:sport_id' => 'events#index'
      get 'events/sports/:sport_id/page/:page' => 'events#index'
      get 'users/events/going' => 'events#going'
      get 'users/events/going/page/:page' => 'events#going'
      get 'users/events/going/sports/:sport_id' => 'events#going'
      get 'users/events/going/sports/:sport_id/page/:page' => 'events#going'

      post 'contactlists' => 'contactlist#searchfriends'
    end
  end

end

app/views/pages/index.html.erb
<!--<h1>TOWL</h1>-->

<!--<% if current_user %>-->
    Hi, <%= @current.full_name %> | <%= link_to "Log out", logout_path, method: "delete" %>
<!--<% else %>-->
    <!--<%= link_to "Log in", login_path %>-->
<!--<% end %>-->
<!--<p id="notice"><%= notice %></p>-->



<!-- Part 1 -->
<div class="question-main-container" id="question1" rel="1">
    <div class="header">
      <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_01.jpg">
      <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
    </div>
    <div class="main-content">

      <div>
        <div class="progresser"></div>
        <div class="progresser-dot selected"><div><div></div></div>01</div>
        <div class="progresser"></div>
        <div class="progresser-dot"><div><div></div></div>02</div>
        <div class="progresser"></div>
        <div class="progresser-dot"><div><div></div></div>03</div>
        <div class="progresser"></div>
        <div class="progresser-dot"><div><div></div></div>04</div>
        <div class="progresser"></div>
        <div class="progresser-dot"><div><div></div></div>05</div>
        <div class="progresser"></div>
      </div>

      <div class="question-container">
        <p>Let's get to know you a little better</p>
        <h1>Tell us your name and age</h1>
        <input type="text" placeholder="YOUR NAME" id="txtName"><br><br><input type="text" placeholder="YOUR BIRTHDAY" id="txtBirthday" readonly="true">
        <br>
        <a class="button btnNext" id="next1" href="#" rel="1">NEXT</a>
        <div class="clear"></div>
      </div>
    </div>
    <div class="clear"></div>
</div>


<!-- Part 2 -->
<div class="question-main-container hide" id="question2" rel="2">
  <div class="header">
    <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_02.jpg">
    <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
  </div>
  <div class="main-content">

    <div>
      <div class="progresser"></div>
      <div class="progresser-dot selected"><div><div></div></div>01</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>02</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>03</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>04</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>05</div>
      <div class="progresser"></div>
    </div>

    <div class="question-container">
      <p>Let's get to know you a little better</p>
      <h1>Are you</h1>
      <a class="checkbox cbGender selected" id="cbMale" href="#">MALE</a>
      <a class="checkbox cbGender" id="cbFemale" href="#">FEMALE</a>
      <br><br><div style="height:22px; margin:0; padding:0;"></div>
      <br>
      <a class="button btnBack" id="back2" href="#" rel="2">BACK</a>
      <a class="button btnNext" id="next2" href="#" rel="2">NEXT</a>
      <div class="clear"></div>
    </div>
  </div>
</div>


<!-- Part 3 -->
<div class="question-main-container hide" id="question3" rel="3">
  <div class="header">
    <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_03.jpg">
    <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
  </div>
  <div class="main-content">

    <div>
      <div class="progresser"></div>
      <div class="progresser-dot selected"><div><div></div></div>01</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>02</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>03</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>04</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>05</div>
      <div class="progresser"></div>
    </div>

    <div class="question-container">
      <p>Let's get to know you a little better</p>
      <h1>Pick your favourite sport</h1>
      <select id="cbSports" >
        <option>RUNNING</option>
        <option>BADMINTON</option>
        <option>FUTSAL</option>
        <option>HIKING</option>
        <option>CYCLING</option>
        <option>BASKETBALL</option>
        <option>OTHERS</option>
      </select><br><br>
      <input type="text" placeholder="OTHERS (PLEASE SPECIFY)" id="txtOtherSports">
      <br>
      <a class="button btnBack" id="back3" href="#" rel="3">BACK</a>
      <a class="button btnNext" id="next3" href="#" rel="3">NEXT</a>
      <div class="clear"></div>
    </div>
  </div>
</div>

<!-- Part 4 -->
<div class="question-main-container hide" id="question4" rel="4">
  <div class="header">
    <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_04.jpg">
    <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
  </div>
  <div class="main-content">

    <div>
      <div class="progresser"></div>
      <div class="progresser-dot selected"><div><div></div></div>01</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>02</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>03</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>04</div>
      <div class="progresser"></div>
      <div class="progresser-dot"><div><div></div></div>05</div>
      <div class="progresser"></div>
    </div>

    <div class="question-container">
      <p>Let's get to know you a little better</p>
      <h1>Do you play sports</h1>
      <select id="cbPurpose" >
        <option>TO BE GOOD/BETTER AT IT</option>
        <option>TO GET HEALTHIER</option>
        <option>TO MAKE NEW FRIENDS</option>
        <option>FOR FUN</option>
        <option>TO GET OUT OF THE COUCH</option>
      </select>
      <br><br><div style="height:22px; margin:0; padding:0;"></div>
      <br>
      <a class="button btnBack" id="back4" href="#" rel="4">BACK</a>
      <a class="button btnNext" id="next4" href="#" rel="4">NEXT</a>
      <div class="clear"></div>
    </div>
  </div>
  <div class="clear"></div>
</div>

<!-- Part 5 -->
<div class="question-main-container hide" id="question5" rel="5">
  <div class="header">
    <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_05.jpg">
    <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
  </div>
  <div class="main-content">

    <div>
      <div class="progresser"></div>
      <div class="progresser-dot selected"><div><div></div></div>01</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>02</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>03</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>04</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>05</div>
      <div class="progresser"></div>
    </div>

    <div class="question-container">
      <p>Let's get to know you a little better</p>
      <h1>How often do you play?</h1>
      <select id="cbOften" >
        <option>ONCE A WEEK</option>
        <option>TWICE A WEEK</option>
        <option>3 OR MORE TIMES A WEEK</option>
        <option>WHEN I FEEL LIKE IT</option>
      </select>
      <br><br><div style="height:22px; margin:0; padding:0;"></div>
      <br>
      <a class="button btnBack" id="back5" href="#" rel="5">BACK</a>
      <a class="button btnNext" id="next5" href="#" rel="5">DONE</a>
      <div class="clear"></div>
    </div>
  </div>
</div>

<!-- Part 6 -->
<div class="question-main-container hide" id="question6" rel="6">
  <div class="header">
    <img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/question/banner_06.jpg">
    <div class="logo"><img src="https://s3-ap-southeast-1.amazonaws.com/towl/web/towl_logo.png"></div>
  </div>
  <div class="main-content">

    <div>
      <div class="progresser"></div>
      <div class="progresser-dot selected"><div><div></div></div>01</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>02</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>03</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>04</div>
      <div class="progresser selected"></div>
      <div class="progresser-dot selected"><div><div></div></div>05</div>
      <div class="progresser selected"></div>
    </div>

    <div class="question-container">
      <h1>Thank you, <span id="lblName">Visitor</span></h1>
      <p>Be the first to experience a revolutionary way of enjoying sports!</p>
      <input type="text" placeholder="ENTER EMAIL" id="txtEmail">
      <br>
      <a class="button btnSubmit" id="btnSubmit" href="#">Submit</a>
      <input type="hidden" id="qkey">
      <div class="clear"></div>
    </div>
  </div>
</div>